import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The sidebar is fully autogenerated from the docs folder structure.
 *
 * - Order is controlled by `sidebar_position` in each file's frontmatter
 *   and by `position` in each directory's `_category_.json`.
 * - Category labels and landing pages are configured in `_category_.json`.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
