import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The sidebar mixes manual + autogenerated entries.
 *
 * - Chapters 1 (Foundations) and 3 (Tech Stack) are configured manually
 *   here to group their many pages into sub-categories so the sidebar
 *   doesn't become a 24-item scroll.
 * - Chapters 2, 4–10 use autogenerated sidebars driven by each chapter's
 *   `_category_.json` + per-page `sidebar_position`.
 * - Chapter 11 (Glossary) is a single file, included as a doc id.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',

    // Chapter 1 — Foundations, grouped
    {
      type: 'category',
      label: '1. Foundations',
      collapsible: true,
      collapsed: false,
      link: {type: 'doc', id: 'foundational-concepts'},
      items: [
        {
          type: 'category',
          label: 'Networking & HTTP',
          collapsible: true,
          collapsed: true,
          items: [
            'client-server',
            'http-basics',
            'http-methods-and-status',
            'http-headers-cookies',
            'dns',
            'cdn-and-edge',
          ],
        },
        {
          type: 'category',
          label: 'Inside the browser',
          collapsible: true,
          collapsed: true,
          items: ['browser-runtime', 'rendering-pipeline'],
        },
        {
          type: 'category',
          label: 'Rendering strategies',
          collapsible: true,
          collapsed: true,
          items: [
            'rendering-strategies',
            'ssg',
            'ssr',
            'csr',
            'isr-streaming-ppr',
            'spa-mpa-hybrid',
          ],
        },
        {
          type: 'category',
          label: 'APIs',
          collapsible: true,
          collapsed: true,
          items: ['apis-rest', 'apis-graphql-trpc', 'apis-realtime'],
        },
        {
          type: 'category',
          label: 'Data',
          collapsible: true,
          collapsed: true,
          items: ['databases-sql', 'databases-nosql', 'databases-choosing'],
        },
        {
          type: 'category',
          label: 'Auth',
          collapsible: true,
          collapsed: true,
          items: ['authentication', 'authorization'],
        },
        {
          type: 'category',
          label: 'Deployment',
          collapsible: true,
          collapsed: true,
          items: ['deployment-pyramid', 'deployment-stages'],
        },
      ],
    },

    // Chapter 2 — Lifecycle (autogen, already-reasonable size)
    {type: 'autogenerated', dirName: '02-lifecycle'},

    // Chapter 3 — Tech Stack, grouped by layer
    {
      type: 'category',
      label: '3. Tech Stack',
      collapsible: true,
      collapsed: false,
      link: {type: 'doc', id: 'tech-stack-decoded'},
      items: [
        {
          type: 'category',
          label: 'Frontend',
          collapsible: true,
          collapsed: true,
          items: ['languages', 'frontend-frameworks', 'styling', 'state-management'],
        },
        {
          type: 'category',
          label: 'Build & dev tools',
          collapsible: true,
          collapsed: true,
          items: ['build-tools', 'package-managers', 'code-quality', 'editors-ai'],
        },
        {
          type: 'category',
          label: 'Backend & APIs',
          collapsible: true,
          collapsed: true,
          items: ['backend-frameworks', 'apis'],
        },
        {
          type: 'category',
          label: 'Data',
          collapsible: true,
          collapsed: true,
          items: ['databases', 'orms'],
        },
        {
          type: 'category',
          label: 'Services & integrations',
          collapsible: true,
          collapsed: true,
          items: [
            'authentication-tools',
            'background-jobs',
            'services',
            'ai-infrastructure',
          ],
        },
        {
          type: 'category',
          label: 'Infrastructure',
          collapsible: true,
          collapsed: true,
          items: ['hosting', 'devops', 'observability-tools'],
        },
      ],
    },

    // Chapters 4–10 — autogen (already reasonable per-chapter sizes)
    {type: 'autogenerated', dirName: '04-solo'},
    {type: 'autogenerated', dirName: '05-startup'},
    {type: 'autogenerated', dirName: '06-enterprise'},
    {type: 'autogenerated', dirName: '07-comparison'},
    {type: 'autogenerated', dirName: '08-decisions'},
    {type: 'autogenerated', dirName: '09-ai'},
    {type: 'autogenerated', dirName: '10-career'},

    // Chapter 11 — Glossary (single file)
    'glossary',
  ],
};

export default sidebars;
