import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar mixes manual + autogenerated entries.
 *
 * - Chapters 1 (Foundations) and 4 (Tech Stack) are configured manually
 *   here to group their many pages into sub-categories so the sidebar
 *   doesn't become a 24-item scroll. Each sub-category has a
 *   `generated-index` landing page so clicking the category name lands
 *   on a friendly grid summary instead of just expanding the menu.
 * - Chapters 2 (Roadmap), 3, 5–11 use autogenerated sidebars driven by
 *   each chapter's `_category_.json` + per-page `sidebar_position`.
 * - Chapter 12 (Glossary) is a single file, included as a doc id.
 *
 * Note: Docusaurus 3.x doc ids are prefixed by their parent directory.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',

    // Chapter 1 — Foundations, grouped
    {
      type: 'category',
      label: '1. Foundations',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'foundations/foundational-concepts'},
      items: [
        {
          type: 'category',
          label: 'Networking & HTTP',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Networking & HTTP',
            description:
              'How bytes get from server to user — the client/server model, HTTP, DNS, and CDNs.',
            slug: '/foundations/networking',
          },
          items: [
            'foundations/client-server',
            'foundations/http-basics',
            'foundations/http-methods-and-status',
            'foundations/http-headers-cookies',
            'foundations/dns',
            'foundations/cdn-and-edge',
          ],
        },
        {
          type: 'category',
          label: 'Inside the browser',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Inside the browser',
            description:
              'What actually happens between "page loads" and "page shows" — the browser as a runtime, and the rendering pipeline.',
            slug: '/foundations/browser',
          },
          items: [
            'foundations/browser-runtime',
            'foundations/rendering-pipeline',
          ],
        },
        {
          type: 'category',
          label: 'Rendering strategies',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Rendering strategies',
            description:
              'Who builds the HTML, and when? SSG, SSR, CSR, plus the modern hybrids (ISR, streaming, RSC, PPR).',
            slug: '/foundations/rendering',
          },
          items: [
            'foundations/rendering-strategies',
            'foundations/ssg',
            'foundations/ssr',
            'foundations/csr',
            'foundations/isr-streaming-ppr',
            'foundations/spa-mpa-hybrid',
          ],
        },
        {
          type: 'category',
          label: 'APIs',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'APIs',
            description:
              'How frontends and backends actually talk: REST, GraphQL, tRPC, gRPC, WebSockets, SSE.',
            slug: '/foundations/apis',
          },
          items: [
            'foundations/apis-rest',
            'foundations/apis-graphql-trpc',
            'foundations/apis-realtime',
            'foundations/webrtc',
            'foundations/message-queues',
          ],
        },
        {
          type: 'category',
          label: 'Data',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Data',
            description:
              'Where your data lives — relational vs NoSQL, search, file storage, and how to choose without overthinking.',
            slug: '/foundations/data',
          },
          items: [
            'foundations/databases-sql',
            'foundations/databases-nosql',
            'foundations/databases-choosing',
            'foundations/search',
            'foundations/files-and-media',
          ],
        },
        {
          type: 'category',
          label: 'Auth & security',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Auth & security',
            description:
              'Who can do what — authentication, authorization, and the broader web security surface (XSS, CSRF, CSP, SQLi, SSRF, supply chain).',
            slug: '/foundations/auth',
          },
          items: [
            'foundations/authentication',
            'foundations/authorization',
            'foundations/web-security',
          ],
        },
        {
          type: 'category',
          label: 'Deployment & infrastructure',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Deployment & infrastructure',
            description:
              'Source → CI → artifact → registry → deploy → runtime → CDN → user. Plus containers, orchestration, and the edge.',
            slug: '/foundations/deployment',
          },
          items: [
            'foundations/deployment-pyramid',
            'foundations/deployment-stages',
            'foundations/containers',
            'foundations/edge-computing',
          ],
        },
        {
          type: 'category',
          label: 'Programming concepts',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Programming concepts',
            description:
              'The conceptual layer beneath everything else — the event loop, concurrency primitives, idempotency, and the distributed-systems realities you cannot ignore once you scale past one machine.',
            slug: '/foundations/programming-concepts',
          },
          items: [
            'foundations/concurrency',
            'foundations/distributed-systems',
          ],
        },
        {
          type: 'category',
          label: 'Production patterns',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Production patterns',
            description:
              'The "make it survive real users" toolkit — rate limiting, caching, secrets/keys, observability, testing, debugging. The things you wish you had the first time something burned down at 3am.',
            slug: '/foundations/production-patterns',
          },
          items: [
            'foundations/rate-limiting',
            'foundations/caching',
            'foundations/secrets-and-keys',
            'foundations/observability-fundamentals',
            'foundations/testing',
            'foundations/debugging',
          ],
        },
        {
          type: 'category',
          label: 'Quality, performance & a11y',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Quality, performance & a11y',
            description:
              'How a product feels — Core Web Vitals, accessibility (WCAG, ARIA, keyboard, screen readers), and the perceived-performance tricks.',
            slug: '/foundations/quality',
          },
          items: [
            'foundations/performance',
            'foundations/accessibility',
          ],
        },
        {
          type: 'category',
          label: 'Realtime collaboration',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Realtime collaboration',
            description:
              'How multiple users edit the same state simultaneously — CRDTs, Yjs, the Google-Docs problem solved.',
            slug: '/foundations/realtime-collab',
          },
          items: [
            'foundations/crdts',
          ],
        },
        {
          type: 'category',
          label: 'Localization & SEO',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Localization & SEO',
            description:
              'Reaching users where they are — internationalization (i18n / l10n) and the technical SEO foundations developers actually own.',
            slug: '/foundations/localization-seo',
          },
          items: [
            'foundations/i18n',
            'foundations/seo',
          ],
        },
        {
          type: 'category',
          label: 'Commerce & comms',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Commerce & comms',
            description:
              'Taking money on the internet (Stripe, subscriptions, webhooks, PCI scope) and reaching inboxes (SPF/DKIM/DMARC, deliverability).',
            slug: '/foundations/commerce-comms',
          },
          items: [
            'foundations/payments',
            'foundations/email',
          ],
        },
        'foundations/foundations-checkpoint',
      ],
    },

    // Chapter 2 — Roadmap (the learning progression — staged curriculum,
    // modern-stack tier picks, foundations beyond the stack, meta-skills)
    {
      type: 'category',
      label: '2. Roadmap',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'roadmap/roadmap-overview'},
      items: [{type: 'autogenerated', dirName: '02-roadmap'}],
    },

    // Chapter 3 — Lifecycle (autogen, wrapped so it renders as a chapter category)
    {
      type: 'category',
      label: '3. Lifecycle',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'lifecycle/development-lifecycle'},
      items: [{type: 'autogenerated', dirName: '03-lifecycle'}],
    },

    // Chapter 4 — Tech Stack, grouped by layer
    {
      type: 'category',
      label: '4. Tech Stack',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'stack/tech-stack-decoded'},
      items: [
        {
          type: 'category',
          label: 'Frontend',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Frontend',
            description:
              'Languages, frameworks, styling, and state management — everything that runs in the browser.',
            slug: '/stack/frontend',
          },
          items: [
            'stack/languages',
            'stack/typescript-advanced',
            'stack/frontend-frameworks',
            'stack/frontend-frameworks-advanced',
            'stack/styling',
            'stack/styling-advanced',
            'stack/state-management',
          ],
        },
        {
          type: 'category',
          label: 'Build & dev tools',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Build & dev tools',
            description:
              'Build tools, package managers, code quality, editors, and AI coding assistants.',
            slug: '/stack/build-and-tools',
          },
          items: [
            'stack/build-tools',
            'stack/package-managers',
            'stack/code-quality',
            'stack/editors-ai',
          ],
        },
        {
          type: 'category',
          label: 'Backend & APIs',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Backend & APIs',
            description:
              'Server frameworks and API styles — what runs on the server and how clients talk to it.',
            slug: '/stack/backend',
          },
          items: ['stack/backend-frameworks', 'stack/apis', 'stack/apis-advanced'],
        },
        {
          type: 'category',
          label: 'Data',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Data (tools)',
            description:
              'Databases and ORMs — the concrete tools you reach for at each scale.',
            slug: '/stack/data',
          },
          items: ['stack/databases', 'stack/databases-advanced', 'stack/orms'],
        },
        {
          type: 'category',
          label: 'Services & integrations',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Services & integrations',
            description:
              'Auth-as-a-service, background jobs, payments/email/files/video, and the AI layer.',
            slug: '/stack/services-integrations',
          },
          items: [
            'stack/authentication-tools',
            'stack/background-jobs',
            'stack/services',
            'stack/ai-infrastructure',
          ],
        },
        {
          type: 'category',
          label: 'Infrastructure',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Infrastructure',
            description:
              'Where the code actually runs — hosting platforms, DevOps tooling, and observability stacks.',
            slug: '/stack/infrastructure',
          },
          items: [
            'stack/hosting',
            'stack/devops',
            'stack/observability-tools',
          ],
        },
        'stack/stack-checkpoint',
      ],
    },

    // ── Part C — Infrastructure & Scale ──────────────────────────────
    // The technical core: where code runs, how to keep it running, and
    // how it behaves once it spans many machines. (Dirs keep their old
    // numeric prefixes; chapter order/numbers are driven by THIS array.)

    // Chapter 5 — Cloud Platforms
    {
      type: 'category',
      label: '5. Cloud Platforms',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'cloud/cloud-platforms'},
      items: [{type: 'autogenerated', dirName: '12-cloud'}],
    },
    // Chapter 6 — SRE & Operations
    {
      type: 'category',
      label: '6. SRE & Operations',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'operations/operations'},
      items: [{type: 'autogenerated', dirName: '13-operations'}],
    },
    // Chapter 7 — Distributed Systems
    {
      type: 'category',
      label: '7. Distributed Systems',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'distributed-systems/distributed-systems'},
      items: [{type: 'autogenerated', dirName: '14-distributed-systems'}],
    },

    // ── Part D — Specializations ─────────────────────────────────────

    // Chapter 8 — AI Integration
    {
      type: 'category',
      label: '8. AI Integration',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'ai/ai-integration'},
      items: [{type: 'autogenerated', dirName: '10-ai'}],
    },
    // Chapter 9 — Mobile & Other Ecosystems
    {
      type: 'category',
      label: '9. Mobile & Other Ecosystems',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'ecosystems/ecosystems'},
      items: [{type: 'autogenerated', dirName: '15-ecosystems'}],
    },

    // ── Part E — Workflows by Scale ──────────────────────────────────

    // Chapter 10 — Solo / Personal
    {
      type: 'category',
      label: '10. Solo / Personal',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'solo/personal-website-workflow'},
      items: [{type: 'autogenerated', dirName: '05-solo'}],
    },
    // Chapter 11 — Startup / Small Co.
    {
      type: 'category',
      label: '11. Startup / Small Co.',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'startup/small-company-workflow'},
      items: [{type: 'autogenerated', dirName: '06-startup'}],
    },
    // Chapter 12 — Enterprise
    {
      type: 'category',
      label: '12. Enterprise',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'enterprise/large-company-workflow'},
      items: [{type: 'autogenerated', dirName: '07-enterprise'}],
    },
    // Chapter 13 — Comparison
    {
      type: 'category',
      label: '13. Comparison',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'comparison/comparison'},
      items: [{type: 'autogenerated', dirName: '08-comparison'}],
    },

    // ── Part F — Judgment & Growth ───────────────────────────────────

    // Chapter 14 — Decisions
    {
      type: 'category',
      label: '14. Decisions',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'decisions/decision-frameworks'},
      items: [{type: 'autogenerated', dirName: '09-decisions'}],
    },
    // Chapter 15 — Career
    {
      type: 'category',
      label: '15. Career',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'career/career-path'},
      items: [{type: 'autogenerated', dirName: '11-career'}],
    },

    // Chapter 16 — Product-Minded & Forward-Deployed Engineering
    {
      type: 'category',
      label: '16. Product-Minded Engineering',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'product-minded/product-minded-overview'},
      items: [{type: 'autogenerated', dirName: '17-product-minded'}],
    },

    // Chapter 17 — Glossary
    'glossary',
  ],
};

export default sidebars;
