import {useEffect} from 'react';
import {useLocation} from '@docusaurus/router';

/**
 * Scrolls + flashes a section when the user arrived via a "revisit" link
 * from a quiz answer (URL contains ?revisit=1 + a heading anchor).
 *
 * Heading anchors are auto-generated by Docusaurus from each h2/h3, e.g.
 *   ## Important cookie attributes  -> id="important-cookie-attributes"
 *
 * Authors who want a more specific highlight target on a non-heading
 * paragraph can wrap that paragraph in plain HTML:
 *
 *   <div id="my-target">...content...</div>
 *
 * The Quiz's <Question revisit={{to: "/docs/...#my-target"}} /> appends
 * ?revisit=1 automatically (via revisitTo helper) so highlighting fires.
 */
export default function RevisitHighlight(): null {
  const location = useLocation();

  useEffect(() => {
    if (typeof window === 'undefined') return;
    const params = new URLSearchParams(location.search);
    if (params.get('revisit') !== '1') return;
    const hash = location.hash?.replace(/^#/, '');
    if (!hash) return;

    // Wait one tick for the page to render before scrolling/highlighting.
    let cancelled = false;
    let highlighted: HTMLElement[] = [];
    const tryHighlight = (attempt = 0) => {
      if (cancelled) return;
      const el = document.getElementById(hash);
      if (!el) {
        if (attempt < 20) {
          window.setTimeout(() => tryHighlight(attempt + 1), 100);
        }
        return;
      }

      // Find the "section" to highlight. If the element is a heading,
      // highlight the heading + the following content until the next
      // same-or-higher level heading.
      const target = findHighlightRange(el);

      // Smooth scroll the heading into view.
      el.scrollIntoView({behavior: 'smooth', block: 'start'});

      // Add highlight class to every element in the range.
      highlighted = target;
      target.forEach((node) => node.classList.add('revisit-highlight'));

      // Strip the ?revisit=1 from the URL after a beat so a normal
      // refresh doesn't keep re-firing the animation.
      window.setTimeout(() => {
        const url = new URL(window.location.href);
        url.searchParams.delete('revisit');
        window.history.replaceState({}, '', url.toString());
      }, 600);

      // Remove highlight after a longer pause so the reader has time
      // to scan the area.
      window.setTimeout(() => {
        target.forEach((node) => node.classList.remove('revisit-highlight'));
      }, 6000);
    };

    tryHighlight();
    return () => {
      cancelled = true;
      highlighted.forEach((node) => node.classList.remove('revisit-highlight'));
    };
  }, [location.pathname, location.search, location.hash]);

  return null;
}

/**
 * Walk forward from a heading element collecting sibling nodes until we
 * hit another heading at the same or higher level (smaller H number).
 * For non-heading targets, just return the element itself.
 */
function findHighlightRange(start: HTMLElement): HTMLElement[] {
  const isHeading = /^H[1-6]$/.test(start.tagName);
  if (!isHeading) return [start];

  const myLevel = parseInt(start.tagName.slice(1), 10);
  const out: HTMLElement[] = [start];
  let cur: Element | null = start.nextElementSibling;
  while (cur) {
    if (/^H[1-6]$/.test(cur.tagName)) {
      const lvl = parseInt(cur.tagName.slice(1), 10);
      if (lvl <= myLevel) break;
    }
    out.push(cur as HTMLElement);
    cur = cur.nextElementSibling;
  }
  return out;
}
