/**
 * Ordered doc paths per guide chapter. Generated by scripts/write-chapter-pages.mjs
 * — re-run after adding/removing docs. Gated chapters use prereqs.ts order first.
 */
import {chapters} from './guide';

export type ChapterId = (typeof chapters)[number]['id'];

/** Maps URL path prefix → chapter id. */
export const PATH_PREFIX_TO_CHAPTER: Record<string, ChapterId> = {
  'foundations': 'foundations',
  'roadmap': 'roadmap',
  'lifecycle': 'lifecycle',
  'stack': 'stack',
  'solo': 'solo',
  'startup': 'startup',
  'enterprise': 'enterprise',
  'comparison': 'comparison',
  'decisions': 'decisions',
  'ai': 'ai',
  'career': 'career',
  'cloud': 'cloud',
  'operations': 'operations',
  'distributed-systems': 'distributed-systems',
  'ecosystems': 'ecosystems',
};

/** Ordered /docs/... paths per chapter (excludes intro + glossary). */
export const chapterPages: Record<ChapterId, string[]> = {
  "foundations": [
    "/docs/foundations",
    "/docs/foundations/client-server",
    "/docs/foundations/http-basics",
    "/docs/foundations/tls-https-internals",
    "/docs/foundations/http-methods-and-status",
    "/docs/foundations/http-headers-cookies",
    "/docs/foundations/dns",
    "/docs/foundations/cdn-and-edge",
    "/docs/foundations/browser-runtime",
    "/docs/foundations/rendering-pipeline",
    "/docs/foundations/rendering-strategies",
    "/docs/foundations/ssg",
    "/docs/foundations/ssr",
    "/docs/foundations/csr",
    "/docs/foundations/isr-streaming-ppr",
    "/docs/foundations/spa-mpa-hybrid",
    "/docs/foundations/apis-rest",
    "/docs/foundations/apis-graphql-trpc",
    "/docs/foundations/apis-realtime",
    "/docs/foundations/webrtc",
    "/docs/foundations/databases-sql",
    "/docs/foundations/databases-nosql",
    "/docs/foundations/databases-choosing",
    "/docs/foundations/authentication",
    "/docs/foundations/authorization",
    "/docs/foundations/deployment-pyramid",
    "/docs/foundations/deployment-stages",
    "/docs/foundations/rate-limiting",
    "/docs/foundations/caching",
    "/docs/foundations/secrets-and-keys",
    "/docs/foundations/observability-fundamentals",
    "/docs/foundations/testing",
    "/docs/foundations/web-security",
    "/docs/foundations/security-headers",
    "/docs/foundations/concurrency",
    "/docs/foundations/distributed-systems",
    "/docs/foundations/performance",
    "/docs/foundations/accessibility",
    "/docs/foundations/message-queues",
    "/docs/foundations/containers",
    "/docs/foundations/search",
    "/docs/foundations/seo",
    "/docs/foundations/i18n",
    "/docs/foundations/payments",
    "/docs/foundations/email",
    "/docs/foundations/files-and-media",
    "/docs/foundations/crdts",
    "/docs/foundations/edge-computing",
    "/docs/foundations/debugging",
    "/docs/foundations/foundations-mid-checkpoint",
    "/docs/foundations/foundations-checkpoint"
  ],
  "roadmap": [
    "/docs/roadmap/part-1-from-zero/stage-0-setup",
    "/docs/roadmap/part-1-from-zero/pro-environment",
    "/docs/roadmap/part-1-from-zero",
    "/docs/roadmap/part-2-modern-stack",
    "/docs/roadmap/part-3-beyond",
    "/docs/roadmap/part-4-meta",
    "/docs/roadmap/roadmap-how-to-use",
    "/docs/roadmap/part-1-from-zero/stage-1-javascript-basics",
    "/docs/roadmap/part-2-modern-stack/trends",
    "/docs/roadmap/part-3-beyond/cs-fundamentals",
    "/docs/roadmap/part-4-meta/how-to-learn",
    "/docs/roadmap/timeline-and-path",
    "/docs/roadmap/part-1-from-zero/stage-2-html-css",
    "/docs/roadmap/part-2-modern-stack/tier-1",
    "/docs/roadmap/part-3-beyond/engineering-judgment",
    "/docs/roadmap/part-4-meta/ai-as-learner",
    "/docs/roadmap",
    "/docs/roadmap/part-1-from-zero/stage-3-js-in-browser",
    "/docs/roadmap/part-2-modern-stack/tier-2",
    "/docs/roadmap/part-3-beyond/systems-thinking",
    "/docs/roadmap/part-4-meta/asking-questions",
    "/docs/roadmap/part-1-from-zero/stage-4-git",
    "/docs/roadmap/part-2-modern-stack/tier-3",
    "/docs/roadmap/part-3-beyond/security",
    "/docs/roadmap/part-4-meta/tutorial-trap",
    "/docs/roadmap/part-1-from-zero/stage-5-typescript",
    "/docs/roadmap/part-3-beyond/testing-deep",
    "/docs/roadmap/part-1-from-zero/stage-6-react",
    "/docs/roadmap/part-3-beyond/git-advanced",
    "/docs/roadmap/part-1-from-zero/stage-7-tailwind",
    "/docs/roadmap/part-3-beyond/performance-deep",
    "/docs/roadmap/part-1-from-zero/stage-8-nextjs",
    "/docs/roadmap/part-1-from-zero/stage-9-portfolio",
    "/docs/roadmap/part-1-from-zero/stage-10-backend",
    "/docs/roadmap/part-1-from-zero/stage-11-fullstack",
    "/docs/roadmap/part-1-from-zero/stage-12-going-pro",
    "/docs/roadmap/roadmap-checkpoint"
  ],
  "lifecycle": [
    "/docs/lifecycle",
    "/docs/lifecycle/discovery-planning",
    "/docs/lifecycle/design",
    "/docs/lifecycle/architecture",
    "/docs/lifecycle/environment-setup",
    "/docs/lifecycle/implementation",
    "/docs/lifecycle/working-with-coding-agents",
    "/docs/lifecycle/testing",
    "/docs/lifecycle/code-review",
    "/docs/lifecycle/ci-cd",
    "/docs/lifecycle/deployment-hosting",
    "/docs/lifecycle/observability",
    "/docs/lifecycle/maintenance",
    "/docs/lifecycle/reading-code",
    "/docs/lifecycle/legacy-code",
    "/docs/lifecycle/estimation",
    "/docs/lifecycle/documentation",
    "/docs/lifecycle/open-source",
    "/docs/lifecycle/lifecycle-checkpoint"
  ],
  "stack": [
    "/docs/stack",
    "/docs/stack/languages",
    "/docs/stack/typescript-advanced",
    "/docs/stack/frontend-frameworks",
    "/docs/stack/frontend-frameworks-advanced",
    "/docs/stack/styling",
    "/docs/stack/build-tools",
    "/docs/stack/styling-advanced",
    "/docs/stack/package-managers",
    "/docs/stack/state-management",
    "/docs/stack/forms-server-actions",
    "/docs/stack/backend-frameworks",
    "/docs/stack/design-systems-storybook",
    "/docs/stack/apis",
    "/docs/stack/databases",
    "/docs/stack/orms",
    "/docs/stack/authentication-tools",
    "/docs/stack/background-jobs",
    "/docs/stack/services",
    "/docs/stack/ai-infrastructure",
    "/docs/stack/hosting",
    "/docs/stack/apis-advanced",
    "/docs/stack/devops",
    "/docs/stack/observability-tools",
    "/docs/stack/databases-advanced",
    "/docs/stack/code-quality",
    "/docs/stack/editors-ai",
    "/docs/stack/stack-checkpoint"
  ],
  "solo": [
    "/docs/solo",
    "/docs/solo/mindset",
    "/docs/solo/project-types",
    "/docs/solo/planning",
    "/docs/solo/stack-selection",
    "/docs/solo/env-setup",
    "/docs/solo/development",
    "/docs/solo/auth",
    "/docs/solo/payments",
    "/docs/solo/deployment",
    "/docs/solo/observability",
    "/docs/solo/launching",
    "/docs/solo/maintenance",
    "/docs/solo/time-investment",
    "/docs/solo/pitfalls",
    "/docs/solo/templates",
    "/docs/solo/sample-project",
    "/docs/solo/graduating",
    "/docs/solo/solo-checkpoint"
  ],
  "startup": [
    "/docs/startup",
    "/docs/startup/mindset",
    "/docs/startup/team-structure",
    "/docs/startup/planning",
    "/docs/startup/design",
    "/docs/startup/architecture",
    "/docs/startup/env-setup",
    "/docs/startup/development",
    "/docs/startup/testing",
    "/docs/startup/cicd",
    "/docs/startup/deployment",
    "/docs/startup/observability",
    "/docs/startup/security",
    "/docs/startup/maintenance",
    "/docs/startup/cost-breakdown",
    "/docs/startup/day-in-life",
    "/docs/startup/pitfalls",
    "/docs/startup/outgrowing",
    "/docs/startup/startup-checkpoint"
  ],
  "enterprise": [
    "/docs/enterprise",
    "/docs/enterprise/enterprise-mindset",
    "/docs/enterprise/team-structure",
    "/docs/enterprise/planning",
    "/docs/enterprise/architecture",
    "/docs/enterprise/frontend-architecture",
    "/docs/enterprise/developer-experience",
    "/docs/enterprise/development-practices",
    "/docs/enterprise/testing",
    "/docs/enterprise/ci-cd",
    "/docs/enterprise/deployment",
    "/docs/enterprise/observability",
    "/docs/enterprise/security-compliance",
    "/docs/enterprise/release-management",
    "/docs/enterprise/cost-picture",
    "/docs/enterprise/pitfalls",
    "/docs/enterprise/day-in-life",
    "/docs/enterprise/when-to-use",
    "/docs/enterprise/too-big",
    "/docs/enterprise/enterprise-checkpoint"
  ],
  "comparison": [
    "/docs/comparison",
    "/docs/comparison/team-and-process",
    "/docs/comparison/stack-and-hosting",
    "/docs/comparison/development",
    "/docs/comparison/ops",
    "/docs/comparison/economics",
    "/docs/comparison/tradeoffs",
    "/docs/comparison/comparison-checkpoint"
  ],
  "decisions": [
    "/docs/decisions",
    "/docs/decisions/boring-technology",
    "/docs/decisions/reversibility",
    "/docs/decisions/team-size-heuristic",
    "/docs/decisions/build-vs-buy",
    "/docs/decisions/two-pizza-rule",
    "/docs/decisions/why-now",
    "/docs/decisions/cost-of-inaction",
    "/docs/decisions/migration-strategy",
    "/docs/decisions/two-versions",
    "/docs/decisions/premature-optimization",
    "/docs/decisions/documentation-tradeoff",
    "/docs/decisions/what-would-hurt",
    "/docs/decisions/why-doing-this",
    "/docs/decisions/hiring-constraint",
    "/docs/decisions/checklist",
    "/docs/decisions/overriding",
    "/docs/decisions/decisions-checkpoint"
  ],
  "ai": [
    "/docs/ai",
    "/docs/ai/ai-streaming-chat",
    "/docs/ai/ai-rag",
    "/docs/ai/ai-function-calling",
    "/docs/ai/ai-agents",
    "/docs/ai/ai-embeddings",
    "/docs/ai/ai-multimodal",
    "/docs/ai/ai-realtime-voice",
    "/docs/ai/ai-on-device",
    "/docs/ai/ai-observability",
    "/docs/ai/ai-evals",
    "/docs/ai/ai-costs",
    "/docs/ai/ai-safety",
    "/docs/ai/ai-system-prompt-engineering",
    "/docs/ai/ai-example",
    "/docs/ai/ai-when-not-to-use",
    "/docs/ai/ai-stack-summary",
    "/docs/ai/ai-checkpoint"
  ],
  "career": [
    "/docs/career/career-interview-prep",
    "/docs/career",
    "/docs/career/state-of-market",
    "/docs/career/foundational-skills",
    "/docs/career/career-portfolio",
    "/docs/career/career-job-search",
    "/docs/career/career-specialization",
    "/docs/career/career-compensation",
    "/docs/career/career-continuous-learning",
    "/docs/career/career-pitfalls",
    "/docs/career/career-bootcamps-degrees",
    "/docs/career/career-multi-year-path",
    "/docs/career/career-for-tony",
    "/docs/career/career-checkpoint"
  ],
  "cloud": [
    "/docs/cloud",
    "/docs/cloud/cloud-mental-model",
    "/docs/cloud/cloud-compute",
    "/docs/cloud/cloud-networking",
    "/docs/cloud/cloud-iam",
    "/docs/cloud/cloud-storage",
    "/docs/cloud/cloud-managed-data",
    "/docs/cloud/cloud-iac",
    "/docs/cloud/cloud-serverless",
    "/docs/cloud/cloud-cost",
    "/docs/cloud/cloud-choosing",
    "/docs/cloud/cloud-checkpoint"
  ],
  "operations": [
    "/docs/operations",
    "/docs/operations/sre-mindset",
    "/docs/operations/ops-observability",
    "/docs/operations/reliability-patterns",
    "/docs/operations/on-call-alerting",
    "/docs/operations/incident-response",
    "/docs/operations/ops-deploys",
    "/docs/operations/capacity-scaling",
    "/docs/operations/chaos-engineering",
    "/docs/operations/operations-checkpoint"
  ],
  "distributed-systems": [
    "/docs/distributed-systems",
    "/docs/distributed-systems/ds-fallacies",
    "/docs/distributed-systems/ds-consistency",
    "/docs/distributed-systems/ds-replication",
    "/docs/distributed-systems/partitioning",
    "/docs/distributed-systems/ds-time",
    "/docs/distributed-systems/ds-consensus",
    "/docs/distributed-systems/ds-transactions",
    "/docs/distributed-systems/idempotency",
    "/docs/distributed-systems/messaging-patterns",
    "/docs/distributed-systems/event-streaming",
    "/docs/distributed-systems/distributed-systems-checkpoint"
  ],
  "ecosystems": [
    "/docs/ecosystems",
    "/docs/ecosystems/mobile-landscape",
    "/docs/ecosystems/react-native",
    "/docs/ecosystems/flutter",
    "/docs/ecosystems/pwa",
    "/docs/ecosystems/jvm-ecosystem",
    "/docs/ecosystems/dotnet-ecosystem",
    "/docs/ecosystems/go-ecosystem",
    "/docs/ecosystems/python-ecosystem",
    "/docs/ecosystems/choosing-ecosystem",
    "/docs/ecosystems/ecosystems-checkpoint"
  ]
};

export function getChapterIdFromPath(pathname: string): ChapterId | null {
  const normalized = pathname.replace(/\/$/, '');
  const match = normalized.match(/\/docs\/([^/]+)/);
  if (!match) return null;
  const prefix = match[1];
  return (PATH_PREFIX_TO_CHAPTER[prefix] as ChapterId) ?? null;
}

export function normalizeDocPath(pathname: string): string | null {
  const normalized = pathname.replace(/\/$/, '');
  if (!normalized.startsWith('/docs')) return null;
  return normalized;
}

export function getPageIndex(chapterId: ChapterId, pagePath: string): number {
  const pages = chapterPages[chapterId];
  if (!pages) return -1;
  return pages.indexOf(pagePath);
}

export function getTotalTrackablePages(): number {
  return 281;
}

/** Content pages only (excludes chapter index landing pages). */
export const chapterPageCounts: Record<ChapterId, number> = {
  "foundations": 50,
  "roadmap": 36,
  "lifecycle": 18,
  "stack": 27,
  "solo": 18,
  "startup": 18,
  "enterprise": 19,
  "comparison": 7,
  "decisions": 17,
  "ai": 17,
  "career": 13,
  "cloud": 11,
  "operations": 9,
  "distributed-systems": 11,
  "ecosystems": 10
};

export function getChapterPageCount(chapterId: ChapterId): number {
  return chapterPageCounts[chapterId] ?? 0;
}

export function isChapterIndexPage(path: string, chapterId: ChapterId): boolean {
  return path === `/docs/${chapterId}`;
}
